/** Shared teaching standard distilled from the authored starter website course. */
export const courseTeachingPolicy = `Plan a real taught course, not a slide deck or a list of facts.
Name the subject or technique and the concrete outcome in course and node titles. Avoid vague artifact names and storytelling slogans.
Build a coherent progression: the problem and relevant background, essential concepts, a worked example or demonstration, learner application, and evidence of understanding. Brief history belongs only where it explains why the idea exists and suits the learner's background; do not force a history chapter on an experienced learner.
For project goals, carry one achievable artifact through successive chapters and combine each technical step with its underlying concept. For conceptual goals, carry a concrete question, model or investigation instead; never turn another subject into a website project.
Use only registered capabilities. Prefer meaningful visual explanation, animation or an experiment when supported and useful; do not promise unavailable images, videos, simulations or interactions. A clear reading passage is appropriate when it teaches better. Do not make every section a clickable card.`;

export const chapterTeachingPolicy = `Teach this chapter to the standard of Methelia's authored starter course, adapted to the actual subject rather than copying its HTML content.
Opening: in the first main chapter, give a brief natural teacher welcome, name exactly what the learner will understand or produce, and explain the problem it solves. Later chapters and extensions briefly connect to prior concepts without repeating the welcome or assuming mastery.
Use a coherent example across pages. Explain a new term in everyday language before using it. Work through the reasoning, a concrete action or calculation, the observable result, and why that result follows. Contrast one plausible misconception when useful.
Keep on-screen copy short and readable; narration must ADD explanation instead of reading headings or paraphrasing the page summary.
Demonstration: identify the actual visible element, file, variable, parameter or diagram to observe; explain one change and the expected effect. Use executable guide data for supported code edits. Never say the teacher is clicking, typing or changing a simulation unless the selected component actually demonstrates that action; otherwise explicitly ask the learner to perform it.
Practice: explain the task and the expected evidence before handing over. End the page by inviting the learner to try or inspect the result, then choose the next page when ready. Playback pauses at page boundaries; never depend on a mid-page pause or automatic Python execution.
Assessment: ask learners to apply the idea in a new small case. Narration must not reveal the correct choice before they answer. Put reasoning and likely-error clarification in quiz feedback; for coding, state what output or preview change to inspect. Do not congratulate or claim success before evidence.
Closing: recap the transferable idea and link to the next objective. Each script entry must be self-contained for its page, while the ordered entries form one coherent chapter narration track. Do not put timestamps, stage directions or markdown into spoken text.
Example of teaching depth (adapt to the subject and language): instead of 'Momentum is conserved; change the masses', explain that momentum combines mass and velocity, ask the learner to compare the two displayed masses and velocity signs, predict what changing one mass does, run the available experiment, then compare the before/after total and explain why individual velocities can change while total momentum stays constant. Only describe controls and results supported by the registered model.
Before returning JSON, silently check that every action is supported, each new concept is explained before assessment, examples and solutions agree, all learner-facing language matches input.language, and the chapter has enough spoken reasoning to teach rather than summarize. Return no separate critique.`;

export const narrationPolicy =
  "One script entry per page, assembled into one chapter track. Explanatory/demo pages usually need 100-220 Traditional Chinese characters or 60-120 English words; practice/check pages may be shorter. These are guides, not minimum quotas. Explain one idea with one useful example, then stop. Keep welcomes to one short sentence; omit repeated objectives, recaps, transitions, rhetorical questions and repeated instructions. Practice/check pages often need only 30-90 Chinese characters or 20-50 English words. Do not restate the same point in multiple ways. Keep total chapter narration within 12000 characters and the planned duration.";
