import type {
  IntakeField,
  IntakeQuestion,
} from "../../src/core/intake-question";
import type { LearnerProfile } from "../../src/core/state";

// Deterministic model double only. Production questions are generated by the model.
export function fixtureIntakeQuestion(
  goal: string,
  field: IntakeField,
  answers: Partial<LearnerProfile> = {},
  language = "zh-TW",
): IntakeQuestion {
  const math = /數學|math|calculus|微積分/i.test(goal);
  const linux = /linux/i.test(goal);
  const python = /python/i.test(goal);
  const subject = math
    ? "數學"
    : linux
      ? "Linux"
      : python
        ? "Python"
        : /bread/i.test(goal)
          ? "麵包發酵"
          : "網頁";
  const english = language === "en";
  if (english) {
    const labels: Record<IntakeField, string[]> = {
      experience: [
        "This is new to me",
        "I have tried the basics",
        "I use this regularly",
      ],
      purpose: [
        "Build intuitive understanding",
        "Practice algorithms and procedures",
        "Understand proofs and reasoning",
      ],
      priorKnowledge: [
        "Basic terminology",
        "How examples work",
        "Comparing approaches",
      ],
      depth: [
        "Build a foundation",
        "Apply it independently",
        "Explore advanced reasoning",
      ],
      studyPlan: [
        "Ten minutes with examples",
        "Twenty minutes of practice",
        "Forty-five minutes of exploration",
      ],
    };
    return {
      field,
      title: `How would you like to approach ${goal}? (${field})`,
      description: "Choose what best fits your starting point.",
      placeholder: "Add any relevant background or preferences",
      options: labels[field].map((label, index) => ({
        label,
        value:
          field === "depth"
            ? ["foundation", "applied", "advanced"][index]
            : label,
        description: "",
      })),
    };
  }
  const titles: Record<IntakeField, string> = {
    experience: `你目前接觸過哪些${subject}內容？`,
    purpose: math ? "你想用什麼方式理解數學？" : `你最想用${subject}完成什麼？`,
    priorKnowledge: `學習${subject}時，哪個部分最需要釐清？`,
    depth: `這次想把${subject}學到什麼程度？`,
    studyPlan: `你想怎麼安排${subject}的練習？`,
  };
  const values: Record<IntakeField, string[]> = {
    experience: math
      ? ["只學過基礎代數", "接觸過微積分", "能閱讀大學數學推導"]
      : linux
        ? ["還沒用過終端機", "會切換目錄與查看檔案", "已經管理過伺服器"]
        : [
            `第一次學習${subject}`,
            `試過${subject}的基本例子`,
            `已能獨立應用${subject}`,
          ],
    purpose: math
      ? ["用圖像直觀理解數學架構", "學會演算法與計算步驟", "理解定理證明"]
      : linux
        ? ["日常檔案操作", "理解權限與程序", "伺服器管理概念"]
        : [
            `理解${subject}的原理`,
            `完成一個${subject}小作品`,
            `練習${subject}題型`,
          ],
    priorKnowledge: math
      ? ["函數與圖形的關係", "符號與運算步驟", "抽象定義與證明"]
      : linux
        ? ["檔案路徑", "權限與擁有者", "指令的輸入輸出"]
        : [
            `${subject}的基本術語`,
            `${subject}例子背後的原因`,
            `比較不同${subject}做法`,
          ],
    depth: ["foundation", "applied", "advanced"],
    studyPlan: [
      "每次 10 分鐘，先看一個例子",
      "每次 20 分鐘，邊做邊理解",
      "每次 45 分鐘，練習與推導",
    ],
  };
  return {
    field,
    title: english
      ? `What would help you learn ${goal}? (${field})`
      : titles[field],
    description: answers.experience
      ? english
        ? `Based on your experience: ${answers.experience}`
        : `依照你的起點「${answers.experience}」，我們會調整接下來的例子。`
      : english
        ? "Start with what you already know."
        : "先找到你熟悉的起點，再安排第一個例子。",
    placeholder: english
      ? "Tell us more about your learning goal"
      : `也可以補充你學習${subject}的具體情境`,
    options: values[field].map((value, index) => ({
      label:
        field === "depth"
          ? ["從具體例子建立基礎", "能獨立完成實際任務", "深入推導與比較方法"][
              index
            ]
          : value,
      value,
      description:
        field === "depth"
          ? `${subject} · ${["foundation", "applied", "advanced"][index]}`
          : "",
    })),
  };
}
